import type {
  LoomOSCompiledState,
  LoomOSState,
  StateIdentity,
} from "../src/shared/types";

export const identity: StateIdentity = {
  chatId: "chat/alpha",
  messageId: "message beta",
  swipeId: 2,
};

const gauge = {
  value: 50,
  pct: "50%",
  band: "active",
  color: "accent",
  trend: "steady" as const,
  note: "Stable pressure.",
};

export const compiledState: LoomOSCompiledState = {
  customModuleData: [],
  activeModules: [
    "sceneKernel",
    "deltas",
    "meters",
    "castCore",
    "appearance",
    "castVisuals",
    "clothing",
    "relationships",
    "inventory",
    "worldSpace",
    "storyThreads",
    "continuity",
    "secretsRumors",
    "actionResolver",
    "auditLog",
  ],
  kernel: {
    scene: "A locked observatory",
    location: "North tower",
    timeframe: "Minutes before dawn",
    date: "Third day of winter",
    time: "Pre-dawn",
    elapsed: "Ten minutes",
    weather: "Rain",
    pov: "Mara",
    tone: "Tense and intimate",
    topic: "The missing ledger",
    theme: "Trust under pressure",
    objective: "Find the missing ledger before the guards arrive.",
    summary: "Mara and Iven search the observatory while mistrust builds.",
    currentFocus: "Search the telescope dais.",
    nextFocus: "Choose an escape route.",
    currentRisk: "The guards are approaching.",
    stopMode: "decision",
    stopWhy: "Mara must choose whether to confront Iven.",
    constraints: ["The east stair is blocked.", "The bell has not rung."],
  },
  delta: {
    headline: "Iven concealed a torn ledger page.",
    changedModules: ["deltas", "castCore", "inventory", "storyThreads"],
    changes: [{
      text: "Iven now holds a torn ledger page.",
      age: "this turn",
      module: "inventory",
      importance: "high",
    }],
    carriedForward: ["The east stair remains blocked."],
    newlyEstablished: ["Iven found one torn page."],
  },
  meters: [{
    id: "tension",
    label: "Tension",
    ...gauge,
  }],
  scene: {
    privacy: "semi-private",
    observerCount: 2,
    observerPressure: {
      value: 4,
      pct: "40%",
      band: "watched",
      color: "warning",
      trend: "up",
      note: "Guards are below.",
    },
    crowdNoise: "Muted boots below",
    crowdFlow: "Closing in",
    light: {
      primary: "Moonlight",
      secondary: "Lantern",
      quality: "Low contrast",
      color: "blue",
    },
    spatial: ["The telescope dais overlooks the west ladder."],
    access: {
      exit: "WATCHED",
      lineOfSight: "The west ladder is visible from the gallery.",
      noiseMask: "Rain against the dome",
      items: ["Telescope"],
      people: ["Mara", "Iven"],
    },
    carryover: {
      body: ["Mara has soot on one sleeve."],
      room: ["The east stair is collapsed."],
      social: ["Mara distrusts Iven."],
    },
    items: [{
      name: "Torn ledger page",
      owner: "Iven",
      location: "Inside coat",
      condition: "Soot-stained",
      lastTouch: "Iven concealed it",
      importance: "critical",
    }],
  },
  castMatrix: [{
    id: "mara",
    name: "Mara",
    kind: "pov",
    qty: 1,
    role: "Investigator",
    status: "Searching the upper gallery",
    location: "North tower",
    emotionalState: "Controlled panic",
    intent: "Recover the ledger.",
    pose: "Crouched by the archive desk",
    proximity: "Across the dais from Iven",
    hands: "One hand on the desk",
    awareness: "alerted",
    threat: {
      value: 2,
      pct: "20%",
      band: "low",
      color: "muted",
      note: "Not currently hostile.",
    },
    spotlight: gauge,
    visualAnchor: "Rain-dark coat and soot-marked sleeve.",
    identitySummary: "Investigator protecting her patron.",
    clothingSummary: "Dark coat, gloves, soot on the left sleeve.",
    goals: ["Recover the ledger"],
    relationships: [{ target: "Iven", axis: "Trust", value: -30, pct: "30%", label: "Distrusts", color: "warning", trend: "down", evidence: "Iven concealed a torn page." }],
    leverage: ["Knows the guard rotation"],
    pockets: [{
      name: "Lock pick",
      type: "tool",
      qty: 1,
      condition: "Good",
      known: true,
      changed: false,
    }],
    stableFacts: ["Mara cannot reveal her patron."],
    changed: false,
    appearance: {
      species: "Human",
      ageBand: "Adult",
      height: "Average",
      weight: "Light for her height",
      build: "Lean",
      bodyType: "Slim with subtle curves",
      frame: "Fine-boned",
      proportions: "Long-legged with narrow shoulders and balanced hips",
      silhouette: "Long, narrow silhouette softened by a defined waist and rounded hips",
      shoulders: "Narrow and gently sloped",
      bust: "Modest",
      waist: "Defined",
      hips: "Balanced",
      glutes: "Compact and rounded, proportionate to her slim frame",
      skin: "Fair skin with a cool undertone",
      complexion: "Clear except for faint wind-reddening across the cheeks",
      face: "Heart-shaped face with high cheekbones and a tapered chin",
      facialStructure: "Fine-boned, with an alert brow and a precise jawline",
      hair: "Ink-dark, shoulder-length hair pulled into a practical low knot, with rain-curled wisps at her temples",
      eyes: "Keen storm-grey eyes beneath straight dark brows",
      nose: "Straight, narrow bridge",
      lips: "Defined cupid's bow and a naturally serious resting line",
      uniqueFeatures: "A faint crescent scar beneath the left eye",
      attractiveFeatures: "Expressive grey eyes, elegant cheekbones, a defined waist, and balanced rounded hips",
      presence: "Quiet intensity",
      immutableTraits: ["Dark tied-back hair", "Keen grey eyes"],
      fullDescription: "Mara is a lean, fine-boned adult woman of average height, with a long-legged silhouette, narrow shoulders, a defined waist, and balanced rounded hips. Her ink-dark hair is pulled into a practical low knot, leaving rain-curled wisps around a heart-shaped face with high cheekbones, a straight nose, and a faint crescent scar beneath her left eye. Storm-grey eyes and an alert brow give her an incisive, watchful beauty, while her compact curves and controlled posture keep her presence restrained rather than delicate.",
      anchor: "Preserve Mara's storm-grey eyes, ink-dark low knot, crescent scar, lean long-legged proportions, defined waist, and restrained watchful presence.",
    },
    clothing: {
      summary: "Mara wears a fitted charcoal wool investigator's coat over a smoke-blue linen shirt and high-waisted black trousers, all practical but sharply tailored. The coat follows her narrow shoulders and defined waist before opening over the hips; rain has darkened the hem and soot smears the left sleeve. Close black leather gloves, weathered ankle boots, and a slim cross-body document satchel complete the outfit.",
      silhouette: "Narrow tailored shoulders, cinched waist, straight trouser line, knee-length coat",
      palette: "Charcoal, smoke blue, matte black, weathered brass",
      fabric: "Dense rain-darkened wool, softly wrinkled linen, worn leather, and brushed brass hardware",
      fit: "Close through shoulders and waist with enough ease for movement; trousers skim the hips and taper at the ankle",
      condition: "Rain-damp at the hem, soot-smeared on the left sleeve, otherwise carefully maintained",
      styling: "Collar turned up, shirt buttoned high, coat belt knotted rather than buckled",
      coverage: "High neckline, full sleeves, full-length trousers, knee-length outer layer",
      footwear: "Black leather ankle boots with low stacked heels and wet, scuffed toes",
      accessories: "Close leather gloves, brass watch chain, slim document satchel",
      notable: "Soot on the left sleeve and a fresh tear near one coat pocket",
      layerCount: 5,
      layers: [
        { slot: "outer", text: "Knee-length charcoal wool investigator's coat with a fitted waist and weathered brass closures", state: "Rain-darkened hem, soot-stained left sleeve" },
        { slot: "upper", text: "Smoke-blue linen shirt with a high buttoned collar and narrow cuffs", state: "Softly wrinkled but intact" },
        { slot: "lower", text: "High-waisted matte-black trousers tapered through the ankle", state: "Damp at the cuffs" },
        { slot: "feet", text: "Black leather ankle boots with low stacked heels", state: "Wet and lightly scuffed" },
        { slot: "accessory", text: "Black gloves, brass watch chain, and a slim cross-body document satchel", state: "Gloves marked with archive dust" },
      ],
    },
    currentState: {
      pose: "Crouched by the archive desk",
      proximity: "Across the dais from Iven",
      leftHand: "On the desk",
      rightHand: "Holding a lantern",
      emotion: "Controlled panic",
      intent: "Recover the ledger.",
      physicalTell: "Slight tremor in the hand",
    },
    continuity: {
      lastConfirmed: "This turn",
      uncertainty: [{
        claim: "Iven may have found more than one page",
        confidence: 6,
        label: "POSSIBLE",
      }],
    },
  }],
  worldState: {
    recentEnvironmentalChanges: ["Rain intensified."],
    activeHazards: ["Guards are approaching."],
    rumors: [{
      rumor: "The Regent keeps a private ledger.",
      source: "Court staff",
      credibility: 8,
      pct: "80%",
      color: "warning",
    }],
    secrets: [{
      secret: "Iven found a torn page.",
      visibleHint: "Soot on his glove.",
      knownBy: ["Iven"],
    }],
      loadedSigns: [{
        thing: "Soot on Iven's glove",
        plantedBy: "Iven",
        payoffWhen: "Mara looks closely.",
        state: "HEATING",
        evidence: "Iven concealed a torn ledger page.",
        payoffHint: "The soot will connect Iven to the hidden page.",
        changed: false,
      }],
  },
  storyState: {
    goals: [{
      who: "Mara",
      goal: "Recover the ledger",
      status: "ACTIVE",
      note: "The full ledger is still missing.",
    }],
    conflicts: [{
      a: "Mara",
      b: "Iven",
      label: "Withheld evidence",
      severity: 2,
    }],
    threadLoom: [{
      title: "The missing ledger",
      status: "escalating",
      urgency: 5,
      priority: "critical",
      progress: 3,
      pct: "30%",
      color: "danger",
      label: "Escalating",
      summary: "The ledger can expose the court.",
      nextPressure: "The guards reach the tower.",
      participants: ["Mara", "Iven"],
    }],
    stakes: [{
      who: "Mara",
      win: "Expose the Regent.",
      lose: "Her patron is implicated.",
    }],
    countdowns: [{
      title: "Guards breach the door",
      left: 2,
      unit: "turns",
      pct: "30%",
      color: "danger",
    }],
    spotlightQueue: [{
      name: "Iven",
      turnsSince: 3,
      pct: "30%",
      color: "warning",
      need: "soon",
      reason: "Iven has important information to reveal.",
    }],
    autonomyQueue: [{
      who: "Iven",
      action: "Move toward the west ladder.",
      unlessInterruptedBy: "Mara confronts him.",
    }],
  },
  continuityFirewall: {
    establishedFacts: ["The east stair is blocked."],
    antiRetconAnchors: ["Do not route anyone down the east stair."],
    pendingConsequences: [{
      cause: "Guards patrol",
      pending: "The guards are approaching.",
      trigger: "Two turns elapsed",
      urgency: 7,
      status: "ACTIVE",
      evidence: "Bootsteps echo from below.",
      changed: false,
    }],
    offscreenState: ["Guards are below the observatory."],
    bannedNext: [{
      text: "Do not reveal Iven's page to Mara without evidence.",
      reason: "Would short-circuit the mystery arc.",
      scope: "scene",
      source: "system",
    }],
    impossibleNext: ["Using the collapsed east stair."],
      terms: [{
        party: "Mara",
        term: "Do not reveal the patron's identity.",
        risk: "Loss of protection",
        status: "ACCEPTED",
        binding: true,
        evidence: "Mara's loyalty to her patron is established.",
        changed: false,
      }],
      risks: [{
      severity: "high",
      issue: "Do not use the east stair.",
      evidence: "It collapsed two turns ago.",
      recommendation: "Use the roof or west ladder.",
    }],
  },
  tools: {
    actionResolver: {
      userAction: "Search the telescope dais.",
      worldResponse: "The search exposes soot and a torn paper edge.",
      risk: "Guards may hear movement.",
      blockers: ["Low light"],
    },
    dialogueState: null,
    directorStyle: null,
    closenessState: null,
    imagePrompt: null,
  },
  auditLog: [{
    system: "compiler",
    marker: "message beta / swipe 2",
    result: "Valid State V2",
    repaired: false,
    notes: "Core and balanced modules compiled.",
  }],
};

export function makeState(overrides: Partial<LoomOSState> = {}): LoomOSState {
  const base = structuredClone(compiledState);
  return {
    ...base,
    schemaVersion: 2,
    identity,
    generatedAt: "2026-06-07T12:00:00.000Z",
    source: {
      messageCount: 12,
      repaired: false,
      seedIdentity: null,
      connectionId: "connection-1",
    },
    ...overrides,
  };
}
