import type {
  LoomOSCompiledState,
  LoomOSState,
  StateIdentity,
} from "../src/shared/types";

export const identity: StateIdentity = {
  chatId: "chat/alpha",
  messageId: "message beta",
  swipeId: 2,
};

const gauge = {
  value: 50,
  pct: "50%",
  band: "active",
  color: "accent",
  trend: "steady" as const,
  note: "Stable pressure.",
};

export const compiledState: LoomOSCompiledState = {
  customModuleData: [],
  activeModules: [
    "sceneKernel",
    "deltas",
    "meters",
    "castCore",
    "castVisuals",
    "clothing",
    "relationships",
    "inventory",
    "worldSpace",
    "storyThreads",
    "continuity",
    "secretsRumors",
    "actionResolver",
    "auditLog",
  ],
  kernel: {
    scene: "A locked observatory",
    location: "North tower",
    timeframe: "Minutes before dawn",
    date: "Third day of winter",
    time: "Pre-dawn",
    elapsed: "Ten minutes",
    weather: "Rain",
    pov: "Mara",
    tone: "Tense and intimate",
    topic: "The missing ledger",
    theme: "Trust under pressure",
    objective: "Find the missing ledger before the guards arrive.",
    summary: "Mara and Iven search the observatory while mistrust builds.",
    currentFocus: "Search the telescope dais.",
    nextFocus: "Choose an escape route.",
    currentRisk: "The guards are approaching.",
    stopMode: "decision",
    stopWhy: "Mara must choose whether to confront Iven.",
    constraints: ["The east stair is blocked.", "The bell has not rung."],
  },
  delta: {
    headline: "Iven concealed a torn ledger page.",
    changedModules: ["deltas", "castCore", "inventory", "storyThreads"],
    changes: [{
      text: "Iven now holds a torn ledger page.",
      age: "this turn",
      module: "inventory",
      importance: "high",
    }],
    carriedForward: ["The east stair remains blocked."],
    newlyEstablished: ["Iven found one torn page."],
  },
  meters: [{
    id: "tension",
    label: "Tension",
    ...gauge,
  }],
  scene: {
    privacy: "semi-private",
    observerCount: 2,
    observerPressure: {
      value: 4,
      pct: "40%",
      band: "watched",
      color: "warning",
      trend: "up",
      note: "Guards are below.",
    },
    crowdNoise: "Muted boots below",
    crowdFlow: "Closing in",
    light: {
      primary: "Moonlight",
      secondary: "Lantern",
      quality: "Low contrast",
      color: "blue",
    },
    spatial: ["The telescope dais overlooks the west ladder."],
    access: {
      exit: "WATCHED",
      lineOfSight: "The west ladder is visible from the gallery.",
      noiseMask: "Rain against the dome",
      items: ["Telescope"],
      people: ["Mara", "Iven"],
    },
    carryover: {
      body: ["Mara has soot on one sleeve."],
      room: ["The east stair is collapsed."],
      social: ["Mara distrusts Iven."],
    },
    items: [{
      name: "Torn ledger page",
      owner: "Iven",
      location: "Inside coat",
      condition: "Soot-stained",
      lastTouch: "Iven concealed it",
      importance: "critical",
    }],
  },
  castMatrix: [{
    id: "mara",
    name: "Mara",
    kind: "pov",
    qty: 1,
    role: "Investigator",
    status: "Searching the upper gallery",
    location: "North tower",
    emotionalState: "Controlled panic",
    intent: "Recover the ledger.",
    pose: "Crouched by the archive desk",
    proximity: "Across the dais from Iven",
    hands: "One hand on the desk",
    awareness: "alerted",
    threat: {
      value: 2,
      pct: "20%",
      band: "low",
      color: "muted",
      note: "Not currently hostile.",
    },
    spotlight: gauge,
    visualAnchor: "Rain-dark coat and soot-marked sleeve.",
    identitySummary: "Investigator protecting her patron.",
    clothingSummary: "Dark coat, gloves, soot on the left sleeve.",
    goals: ["Recover the ledger"],
    relationships: ["Distrusts Iven"],
    leverage: ["Knows the guard rotation"],
    pockets: [{
      name: "Lock pick",
      type: "tool",
      qty: 1,
      condition: "Good",
      known: true,
    }],
    stableFacts: ["Mara cannot reveal her patron."],
  }],
  worldState: {
    recentEnvironmentalChanges: ["Rain intensified."],
    activeHazards: ["Guards are approaching."],
    rumors: [{
      rumor: "The Regent keeps a private ledger.",
      source: "Court staff",
      credibility: 8,
      pct: "80%",
      color: "warning",
    }],
    secrets: [{
      secret: "Iven found a torn page.",
      visibleHint: "Soot on his glove.",
      knownBy: ["Iven"],
    }],
    loadedSigns: [{
      thing: "Soot on Iven's glove",
      loadedBy: "He handled the hidden page.",
      firesWhen: "Mara looks closely.",
      state: "HEATING",
    }],
  },
  storyState: {
    goals: [{
      who: "Mara",
      goal: "Recover the ledger",
      status: "ACTIVE",
      note: "The full ledger is still missing.",
    }],
    conflicts: [{
      a: "Mara",
      b: "Iven",
      label: "Withheld evidence",
      severity: 2,
    }],
    threadLoom: [{
      title: "The missing ledger",
      status: "escalating",
      urgency: 5,
      priority: "critical",
      progress: 3,
      pct: "30%",
      color: "danger",
      label: "Escalating",
      summary: "The ledger can expose the court.",
      nextPressure: "The guards reach the tower.",
      participants: ["Mara", "Iven"],
    }],
    stakes: [{
      who: "Mara",
      win: "Expose the Regent.",
      lose: "Her patron is implicated.",
    }],
    countdowns: [{
      title: "Guards breach the door",
      left: 2,
      unit: "turns",
      pct: "30%",
      color: "danger",
    }],
    autonomyQueue: [{
      who: "Iven",
      action: "Move toward the west ladder.",
      unlessInterruptedBy: "Mara confronts him.",
    }],
  },
  continuityFirewall: {
    establishedFacts: ["The east stair is blocked."],
    antiRetconAnchors: ["Do not route anyone down the east stair."],
    pendingConsequences: ["The guards are approaching."],
    offscreenState: ["Guards are below the observatory."],
    bannedNext: [{
      text: "Do not reveal Iven's page to Mara without evidence.",
      persistent: false,
    }],
    impossibleNext: ["Using the collapsed east stair."],
    risks: [{
      severity: "high",
      issue: "Do not use the east stair.",
      evidence: "It collapsed two turns ago.",
      recommendation: "Use the roof or west ladder.",
    }],
  },
  tools: {
    actionResolver: {
      userAction: "Search the telescope dais.",
      worldResponse: "The search exposes soot and a torn paper edge.",
      risk: "Guards may hear movement.",
      blockers: ["Low light"],
    },
    dialogueState: null,
    directorStyle: null,
    closenessState: null,
    imagePrompt: null,
  },
  auditLog: [{
    system: "compiler",
    marker: "message beta / swipe 2",
    result: "Valid State V2",
    repaired: false,
    notes: "Core and balanced modules compiled.",
  }],
};

export function makeState(overrides: Partial<LoomOSState> = {}): LoomOSState {
  return {
    ...compiledState,
    schemaVersion: 2,
    identity,
    generatedAt: "2026-06-07T12:00:00.000Z",
    source: {
      messageCount: 12,
      repaired: false,
      seedIdentity: null,
      connectionId: "connection-1",
    },
    ...overrides,
  };
}
